export type ToolCategory = 'all' | 'image' | 'math' | 'text' | 'datetime' | 'units' | 'practical';

export interface ToolCategoryInfo {
  id: ToolCategory;
  nameTr: string;
  icon: string;
}

export const CATEGORIES: ToolCategoryInfo[] = [
  { id: 'all', nameTr: 'Tüm Araçlar', icon: 'Sparkles' },
  { id: 'image', nameTr: 'Görsel & Medya', icon: 'Image' },
  { id: 'math', nameTr: 'Hesaplama & Finans', icon: 'Calculator' },
  { id: 'text', nameTr: 'Metin & Yazı', icon: 'Type' },
  { id: 'datetime', nameTr: 'Tarih & Zaman', icon: 'Clock' },
  { id: 'units', nameTr: 'Ölçü Birimleri', icon: 'ArrowLeftRight' },
  { id: 'practical', nameTr: 'Pratik Günlük', icon: 'Wrench' },
];

export interface ToolItem {
  id: string;
  name: string;
  shortDesc: string;
  category: ToolCategory;
  iconName: string;
  badge?: string;
  keywords: string[];
  gradient: string;
  iconColor: string;
}

export const TOOLS: ToolItem[] = [
  {
    id: 'gorsel-sikistir',
    name: 'Görsel Sıkıştırıcı & Boyutlandırıcı',
    shortDesc: 'Fotoğrafları kalitesini kaybetmeden küçültün, WebP/JPEG formatına dönüştürün.',
    category: 'image',
    iconName: 'ImageDown',
    badge: 'Popüler',
    keywords: ['resim', 'fotoğraf', 'sıkıştırma', 'küçültme', 'webp', 'jpeg', 'boyut', 'kb', 'mb'],
    gradient: 'from-slate-900 to-cyan-950',
    iconColor: 'text-cyan-300',
  },
  {
    id: 'renk-paleti',
    name: 'Renk Seçici & Palet Çıkarıcı',
    shortDesc: 'Resimlerden renk paleti ayıklayın veya HEX, RGB, HSL renk kodları seçin.',
    category: 'image',
    iconName: 'Palette',
    keywords: ['renk', 'hex', 'rgb', 'palet', 'damlalık', 'tasarım', 'ton'],
    gradient: 'from-slate-900 to-fuchsia-950',
    iconColor: 'text-pink-300',
  },
  {
    id: 'kdv-hesaplama',
    name: 'KDV & Tevkifat Hesaplayıcı',
    shortDesc: '%1, %10 ve %20 güncel oranlarla KDV dahil/hariç ve tevkifat hesaplayın.',
    category: 'math',
    iconName: 'Receipt',
    badge: 'Çok Kullanılan',
    keywords: ['kdv', 'vergi', 'tevkifat', 'fatura', 'dahil', 'hariç', 'muhasebe', 'oran'],
    gradient: 'from-slate-900 to-emerald-950',
    iconColor: 'text-emerald-300',
  },
  {
    id: 'indirim-kar',
    name: 'İndirim & Kar Marjı Hesaplayıcı',
    shortDesc: 'Alışveriş indirimlerini, cebinizde kalan tasarrufu ve satış kar marjını görün.',
    category: 'math',
    iconName: 'BadgePercent',
    keywords: ['indirim', 'tasarruf', 'kar', 'marj', 'maliyet', 'fiyat', 'kampanya'],
    gradient: 'from-slate-900 to-amber-950',
    iconColor: 'text-amber-300',
  },
  {
    id: 'yuzde-hesaplama',
    name: 'Hızlı Yüzde Hesaplayıcı',
    shortDesc: 'Bir sayının yüzdesini, değişim oranını ve oransal farkı saniyeler içinde çözün.',
    category: 'math',
    iconName: 'Percent',
    keywords: ['yüzde', 'oran', 'artış', 'azalış', 'pay', 'oranlama'],
    gradient: 'from-slate-900 to-blue-950',
    iconColor: 'text-blue-300',
  },
  {
    id: 'vki-hesaplama',
    name: 'Vücut Kitle İndeksi & İdeal Kilo',
    shortDesc: 'DSÖ standartlarında kilo durumunuzu ve boyunuza uygun sağlıklı kilo aralığını öğrenin.',
    category: 'math',
    iconName: 'Scale',
    badge: 'Sağlık',
    keywords: ['vki', 'bmi', 'kilo', 'boy', 'diyet', 'sağlık', 'obezite', 'ideal kilo'],
    gradient: 'from-slate-900 to-rose-950',
    iconColor: 'text-rose-300',
  },
  {
    id: 'hesap-bolusturucu',
    name: 'Bahşiş & Hesap Bölüştürücü',
    shortDesc: 'Yemek ve etkinlik hesaplarını arkadaşlar arasında adilce paylaştırın.',
    category: 'math',
    iconName: 'Users',
    keywords: ['hesap', 'adisyon', 'bahşiş', 'bölüşme', 'restoran', 'arkadaş', 'paylaşım'],
    gradient: 'from-slate-900 to-purple-950',
    iconColor: 'text-purple-300',
  },
  {
    id: 'kelime-sayaci',
    name: 'Kelime, Karakter & Süre Sayacı',
    shortDesc: 'Harf, boşluksuz karakter, kelime, cümle sayısı ve tahmini okuma süresini ölçün.',
    category: 'text',
    iconName: 'FileText',
    badge: 'Hızlı',
    keywords: ['kelime', 'karakter', 'harf', 'sayac', 'okuma süresi', 'makale', 'ödev'],
    gradient: 'from-slate-900 to-sky-950',
    iconColor: 'text-sky-300',
  },
  {
    id: 'turkce-harf-donusturucu',
    name: 'Türkçe Büyük/Küçük Harf Düzenleyici',
    shortDesc: 'Türkçe İ/ı kurallarına uygun Büyük Harf, Küçük Harf, Başlık ve Cümle düzeni yapın.',
    category: 'text',
    iconName: 'CaseSensitive',
    keywords: ['büyük harf', 'küçük harf', 'türkçe', 'başlık', 'cümle', 'çevirici', 'i ı'],
    gradient: 'from-slate-900 to-violet-950',
    iconColor: 'text-violet-300',
  },
  {
    id: 'metin-temizleyici',
    name: 'Metin Temizleyici & Satır Farkı',
    shortDesc: 'Yinelenen satırları, gereksiz boşlukları ve HTML kodlarını tek dokunuşla silin.',
    category: 'text',
    iconName: 'ListFilter',
    keywords: ['temizleme', 'boşluk', 'kopya', 'satır', 'html temizle', 'fark bul'],
    gradient: 'from-slate-900 to-teal-950',
    iconColor: 'text-teal-300',
  },
  {
    id: 'tarih-farki',
    name: 'İki Tarih Arası Gün & İş Günü Sayacı',
    shortDesc: 'İki tarih arasındaki gün, hafta sonu hariç mesai günü, ay ve yıl farkını bulun.',
    category: 'datetime',
    iconName: 'CalendarDays',
    badge: 'Pratik',
    keywords: ['tarih', 'gün', 'iş günü', 'mesai', 'hafta', 'zaman farkı', 'tatil'],
    gradient: 'from-slate-900 to-indigo-950',
    iconColor: 'text-indigo-300',
  },
  {
    id: 'yas-burc',
    name: 'Detaylı Yaş & Burç Hesaplayıcı',
    shortDesc: 'Yaşadığınız tam gün, saat, sonraki doğum gününüze kalan süre ve astrolojik burcunuz.',
    category: 'datetime',
    iconName: 'CalendarCheck',
    keywords: ['yaş', 'doğum günü', 'burç', 'astroloji', 'kaç yaşındayım', 'gün sayısı'],
    gradient: 'from-slate-900 to-pink-950',
    iconColor: 'text-pink-300',
  },
  {
    id: 'kronometre-sayac',
    name: 'Kronometre & Geri Sayım Sayacı',
    shortDesc: 'Tur zamanlı hassas kronometre ve sesli alarmlı geri sayım zamanlayıcı.',
    category: 'datetime',
    iconName: 'Timer',
    keywords: ['kronometre', 'sayaç', 'zamanlayıcı', 'alarm', 'tur', 'fokus', 'pomodoro'],
    gradient: 'from-slate-900 to-orange-950',
    iconColor: 'text-orange-300',
  },
  {
    id: 'dunya-saatleri',
    name: 'Dünya Saatleri & Zaman Dilimi',
    shortDesc: 'İstanbul, Londra, New York, Tokyo saatleri ve anlık zaman farkı karşılaştırması.',
    category: 'datetime',
    iconName: 'Globe',
    keywords: ['saat', 'dünya saati', 'new york', 'londra', 'tokyo', 'zaman dilimi', 'gmt'],
    gradient: 'from-slate-900 to-cyan-900',
    iconColor: 'text-cyan-300',
  },
  {
    id: 'birim-donusturucu',
    name: 'Ölçü Birimleri Çevirici',
    shortDesc: 'Metre, inç, mil; gram, kg, pound; bayt, MB, GB birimlerini anında birbirine çevirin.',
    category: 'units',
    iconName: 'ArrowLeftRight',
    badge: 'Kapsamlı',
    keywords: ['ölçü', 'birim', 'metre', 'inç', 'kg', 'pound', 'litre', 'galon', 'mb', 'gb'],
    gradient: 'from-slate-900 to-teal-950',
    iconColor: 'text-teal-300',
  },
  {
    id: 'sicaklik-donusturucu',
    name: 'Sıcaklık Çevirici',
    shortDesc: 'Celsius (°C), Fahrenheit (°F) ve Kelvin (K) değerlerini pratikçe dönüştürün.',
    category: 'units',
    iconName: 'Thermometer',
    keywords: ['sıcaklık', 'celsius', 'fahrenheit', 'kelvin', 'derece', 'hava'],
    gradient: 'from-slate-900 to-red-950',
    iconColor: 'text-red-300',
  },
  {
    id: 'qr-kod-olusturucu',
    name: 'QR Kod Oluşturucu & İndirici',
    shortDesc: 'Web sitesi, Wi-Fi şifresi, WhatsApp mesajı ve kartvizit için renkli QR kod üretin.',
    category: 'practical',
    iconName: 'QrCode',
    badge: 'Popüler',
    keywords: ['qr kod', 'karekod', 'barkod', 'wifi qr', 'link', 'whatsapp qr'],
    gradient: 'from-slate-800 to-slate-950',
    iconColor: 'text-blue-300',
  },
  {
    id: 'guclu-parola',
    name: 'Güçlü Şifre & PIN Oluşturucu',
    shortDesc: 'Kırılması imkansız şifreler, kolay hatırlanan parolalar ve banka PIN kodları oluşturun.',
    category: 'practical',
    iconName: 'KeyRound',
    keywords: ['şifre', 'parola', 'pin', 'güvenlik', 'şifre üretici', 'random password'],
    gradient: 'from-slate-900 to-emerald-950',
    iconColor: 'text-emerald-300',
  },
  {
    id: 'rastgele-secici',
    name: 'Rastgele Karar Verici, Çekiliş & Zar',
    shortDesc: 'Listeden rastgele isim/öğe seçin, zar atın veya yazı-tura ile hızlıca karar verin.',
    category: 'practical',
    iconName: 'Shuffle',
    keywords: ['çekiliş', 'rastgele', 'zar', 'yazı tura', 'karar verici', 'kura'],
    gradient: 'from-slate-900 to-purple-950',
    iconColor: 'text-pink-300',
  },
  {
    id: 'dijital-imza',
    name: 'Dijital İmza Çizici & Şeffaf PNG',
    shortDesc: 'Belgeleriniz için ekranda imza atıp arka plansız şeffaf PNG olarak kaydedin.',
    category: 'practical',
    iconName: 'PenTool',
    keywords: ['imza', 'dijital imza', 'çizim', 'şeffaf png', 'belge', 'pdf imza'],
    gradient: 'from-blue-900 to-slate-950',
    iconColor: 'text-sky-200',
  },
  {
    id: 'hizli-not',
    name: 'Hızlı Not & Karalama Defteri',
    shortDesc: 'Tarayıcıyı kapatsanız bile silinmeyen, anında çalışan güvenli kişisel not alanı.',
    category: 'practical',
    iconName: 'StickyNote',
    keywords: ['not', 'karalama', 'defter', 'yazı', 'kaydet', 'scratchpad'],
    gradient: 'from-slate-900 to-amber-950',
    iconColor: 'text-amber-300',
  },
];
